# Generated by Django 2.2.1 on 2019-07-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190717_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='series',
            field=models.ManyToManyField(related_name='watchlists', to='api.Series'),
        ),
    ]
