# Generated by Django 2.2.1 on 2019-07-19 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190717_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmd_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
