# Generated by Django 2.2.1 on 2019-08-08 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_series_tmd_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='first_air_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='overview',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='poster_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='series',
            name='tmd_id',
            field=models.CharField(max_length=100),
        ),
    ]
